<a href="https://colab.research.google.com/github/oamerciful-rgb/math-for-data-science/blob/main/Week6_PDA_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_excel('/content/Global Superstore Orders 2016.xlsx')

# Display the number of rows and columns
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

# List all column names
print("\nColumn names:")
for col in df.columns:
    print(col)

# Show the first five rows
print("\nFirst five rows of the dataset:")
display(df.head())

Number of rows: 51292
Number of columns: 28

Column names:
Row ID
Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Postal Code
City
State
Country
Region
Market
Product ID
Category
Sub-Category
Product Name
Unnamed: 18
Sales
Unnamed: 20
Unnamed: 21
Unnamed: 22
Quantity
Discount
Profit
Shipping Cost
Order Priority

First five rows of the dataset:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,NaN,NaN,70.00,100.0,70.00,2.0,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,NaN,NaN,80.00,100.0,80.00,9.0,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,NaN,NaN,99.00,100.0,99.00,9.0,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,NaN,NaN,90.00,100.0,90.00,5.0,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,NaN,NaN,25.25,100.0,25.25,8.0,0.0,311.5200,903.04,Critical

In [3]:
import pandas as pd

# Load the dataset
df = pd.read_excel('/content/Global Superstore Orders 2016.xlsx')

# Display the number of rows and columns
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

# List all column names
print("\nColumn names:")
for col in df.columns:
    print(col)

# Show the first five rows
print("\nFirst five rows of the dataset:")
display(df.head())

# Display summary statistics for numeric columns
print("\nSummary Statistics:")
display(df.describe())

Number of rows: 51292
Number of columns: 28

Column names:
Row ID
Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Postal Code
City
State
Country
Region
Market
Product ID
Category
Sub-Category
Product Name
Unnamed: 18
Sales
Unnamed: 20
Unnamed: 21
Unnamed: 22
Quantity
Discount
Profit
Shipping Cost
Order Priority

First five rows of the dataset:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,NaN,NaN,70.00,100.0,70.00,2.0,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,NaN,NaN,80.00,100.0,80.00,9.0,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,NaN,NaN,99.00,100.0,99.00,9.0,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,NaN,NaN,90.00,100.0,90.00,5.0,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,NaN,NaN,25.25,100.0,25.25,8.0,0.0,311.5200,903.04,Critical

Summary Statistics:

,Order Date,Ship Date,Postal Code,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost
count,51290,51290,9997.000000,0.0,51279.000000,6.000000,5.0,5.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,2014-05-11 20:31:52.513160192,2014-05-15 19:48:11.370637568,55187.133340,NaN,245.962393,72.850000,100.0,72.850000,3.476545,0.142908,28.610982,26.478567
min,2012-01-01 00:00:00,2012-01-03 00:00:00,1040.000000,NaN,0.000000,25.250000,100.0,25.250000,1.000000,0.000000,-6599.978000,1.002000
25%,2013-06-19 00:00:00,2013-06-23 00:00:00,23223.000000,NaN,30.739500,70.712500,100.0,70.000000,2.000000,0.000000,0.000000,2.610000
50%,2014-07-08 00:00:00,2014-07-12 00:00:00,56301.000000,NaN,85.050000,76.425000,100.0,80.000000,3.000000,0.000000,9.240000,7.790000
75%,2015-05-22 00:00:00,2015-05-26 00:00:00,90008.000000,NaN,250.992000,87.500000,100.0,90.000000,5.000000,0.200000,36.810000,24.450000
max,2015-12-31 00:00:00,2016-01-07 00:00:00,99301.000000,NaN,22638.480000,99.000000,100.0,99.000000,14.000000,0.850000,8399.976000,933.570000
std,NaN,NaN,32068.686012,NaN,485.543151,25.701945,0.0,28.735649,2.278766,0.212280,174.340972,57.251373

In [9]:
df['Profit_Per_Sale'] = df['Profit'] / df['Sales']
print("DataFrame with new 'Profit_Per_Sale' column:")
display(df.head())

DataFrame with new 'Profit_Per_Sale' column:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority,Profit_Per_Sale
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,NaN,70.00,100.0,70.00,2.0,0.0,62.1544,40.77,High,NaN
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,NaN,80.00,100.0,80.00,9.0,0.1,-288.7650,923.63,Critical,NaN
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,NaN,99.00,100.0,99.00,9.0,0.1,919.9710,915.49,Medium,NaN
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,NaN,90.00,100.0,90.00,5.0,0.1,-96.5400,910.16,Medium,NaN
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,NaN,25.25,100.0,25.25,8.0,0.0,311.5200,903.04,Critical,NaN

The `Profit_Per_Sale` column indicates the profit margin for each sale. A higher value means a larger profit generated per unit of sales revenue. It helps to understand the efficiency of each sale in terms of profitability.

In [10]:
highest_profit_ratio_order = df.loc[df['Profit_Per_Sale'].idxmax()]
print("\nOrder with the highest profit ratio:")
display(highest_profit_ratio_order)

Order with the highest profit ratio:

Row ID                                      50981
Order ID                    AG-2015-CL25653-42164
Order Date                    2015-06-09 00:00:00
Ship Date                     2015-06-13 00:00:00
Ship Mode                          Standard Class
Customer ID                              CL-25653
Customer Name                         Clay Ludtke
Segment                                  Consumer
Postal Code                                   NaN
City                                        Saida
State                                       Saida
Country                                   Algeria
Region                               North Africa
Market                                     Africa
Product ID                            OFF-AP-4963
Category                          Office Supplies
Sub-Category                           Appliances
Product Name       KitchenAid Refrigerator, White
Unnamed: 18                                   NaN
Sales                                     1052.16
Unnamed: 20                                   NaN
Unnamed: 21                                   NaN
Unnamed: 22                                   NaN
Quantity                                      2.0
Discount                                      0.0
Profit                                     526.08
Shipping Cost                              147.79
Order Priority                               High
Profit_Per_Sale                               0.5
Name: 1729, dtype: object

The order with the highest profit ratio (Profit_Per_Sale) is displayed above. This indicates the single transaction that yielded the highest profit margin relative to its sales value.

In [11]:
df.to_excel("Cleaned_Global_Superstore.xlsx", index=False)
print("The cleaned data has been saved to 'Cleaned_Global_Superstore.xlsx'")

The cleaned data has been saved to 'Cleaned_Global_Superstore.xlsx'

The saved file is named **`Cleaned_Global_Superstore.xlsx`**.

Exporting data after cleaning and analysis is useful for several reasons:

1.  **Preservation of Work**: It saves all the transformations, new features (like `Profit_Per_Sale`), and cleaning steps applied to the original data. This means you don't have to rerun all the cleaning and processing steps every time you want to use the data.
2.  **Shareability**: The cleaned dataset can be easily shared with others who might need to use it for further analysis, reporting, or building models, without needing access to the original raw data or the processing scripts.
3.  **Foundation for Further Analysis**: It provides a clean, ready-to-use dataset for subsequent stages of a project, such as advanced modeling, dashboard creation, or specific business intelligence tasks.
4.  **Version Control/Reproducibility**: Saving intermediate versions of the data can act as a form of version control, making it easier to revert to a clean state or reproduce results from a specific point in the analysis.
5.  **Performance**: Reading a pre-cleaned file is often faster than loading raw data and then applying all cleaning and preprocessing steps each time.

In [7]:
# Group by Category and calculate total Profit
profit_by_category = df.groupby('Category')['Profit'].sum().reset_index()
print("\nTotal Profit by Category:")
display(profit_by_category.sort_values(by='Profit', ascending=False))

Total Profit by Category:

          Category        Profit
2       Technology  663778.73318
1  Office Supplies  518595.82790
0        Furniture  285082.73020

In [8]:
# Group by Region and calculate total Profit
profit_by_region = df.groupby('Region')['Profit'].sum().reset_index()
print("\nTotal Profit by Region:")
display(profit_by_region.sort_values(by='Profit', ascending=False))

Total Profit by Region:

               Region        Profit
21     Western Europe  218433.50850
7        Eastern Asia  167101.85100
16      Southern Asia  159336.42700
3     Central America  158981.64816
12            Oceania  120089.11200
22         Western US  108418.44890
9          Eastern US   91522.78000
11    Northern Europe   83923.91700
8      Eastern Europe   77084.88000
17    Southern Europe   70109.41800
10       North Africa   57836.25000
18        Southern US   46749.43030
5          Central US   39706.36250
2      Central Africa   35383.71000
1           Caribbean   34571.32104
13      South America   28090.51788
15    Southern Africa   24158.55000
6      Eastern Africa   21900.90900
14  Southeastern Asia   17852.32900
0              Canada   17817.39000
4        Central Asia   -7282.01100
19     Western Africa  -50407.78800
20       Western Asia  -53921.67000

In [6]:
# Sort orders by Profit from highest to lowest
df_sorted_profit_desc = df.sort_values(by='Profit', ascending=False)

print("\nOrders sorted by Profit (highest to lowest) - Top 5 rows:")
display(df_sorted_profit_desc.head())

Orders sorted by Profit (highest to lowest) - Top 5 rows:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
49005,38123,CA-2014-TC20980140-41915,2014-10-03,2014-10-10,Standard Class,TC-209801402,Tamara Chand,Corporate,47905.0,Lafayette,...,NaN,17499.95,NaN,NaN,NaN,5.0,0.0,8399.9760,349.07000,Medium
44250,39450,CA-2015-RB19360140-42087,2015-03-24,2015-03-26,First Class,RB-193601404,Raymond Buch,Consumer,98115.0,Seattle,...,NaN,13999.96,NaN,NaN,NaN,4.0,0.0,6719.9808,20.00054,Medium
25240,35487,CA-2015-HL15040140-42326,2015-11-18,2015-11-23,Standard Class,HL-150401406,Hunter Lopez,Consumer,19711.0,Newark,...,NaN,10499.97,NaN,NaN,NaN,3.0,0.0,5039.9856,363.19000,Medium
421,40336,CA-2014-AB10105140-41991,2014-12-18,2014-12-22,Standard Class,AB-101051402,Adrian Barton,Consumer,48205.0,Detroit,...,NaN,9892.74,NaN,NaN,NaN,13.0,0.0,4946.3700,498.70000,Medium
46297,35395,CA-2012-SC20095140-41174,2012-09-22,2012-09-27,Standard Class,SC-200951402,Sanjit Chand,Consumer,55407.0,Minneapolis,...,NaN,9449.95,NaN,NaN,NaN,5.0,0.0,4630.4755,655.61000,Medium

In [4]:
# Filter rows where Sales are greater than 500
sales_gt_500 = df[df['Sales'] > 500]
print(f"Number of orders with Sales > 500: {len(sales_gt_500)}")
print("\nFirst 5 rows with Sales > 500:")
display(sales_gt_500.head())

Number of orders with Sales > 500: 6744

First 5 rows with Sales > 500:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
14,45794,ES-2015-PO18865139-42018,2015-01-14,2015-01-18,Standard Class,PO-18865139,Patrick O'Donnell,Consumer,NaN,Stockton-on-Tees,...,NaN,2616.960,NaN,NaN,NaN,4.0,0.0,1151.400,832.41,Critical
15,4132,IN-2012-DL128657-40918,2012-01-10,2012-01-11,First Class,DL-128657,Dan Lawera,Consumer,NaN,Brisbane,...,NaN,2221.800,NaN,NaN,NaN,7.0,0.0,622.020,810.25,Critical
16,27704,ID-2014-JB1600059-41873,2014-08-22,2014-08-26,Standard Class,JB-1600059,Joy Bell-,Consumer,NaN,Mataram,...,NaN,3701.520,NaN,NaN,NaN,12.0,0.0,1036.080,804.54,Critical
17,13779,IN-2015-BF1100558-42319,2015-11-11,2015-11-15,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,NaN,1869.588,NaN,NaN,NaN,4.0,0.1,186.948,801.66,Critical
19,12069,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,NaN,7958.580,NaN,NaN,NaN,14.0,0.0,3979.080,778.32,Low

In [5]:
# Filter rows where Sales are greater than 1000
sales_gt_1000 = df[df['Sales'] > 1000]
print(f"Number of orders with Sales > 1000: {len(sales_gt_1000)}")
print("\nFirst 5 rows with Sales > 1000:")
display(sales_gt_1000.head())

Number of orders with Sales > 1000: 2618

First 5 rows with Sales > 1000:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
14,45794,ES-2015-PO18865139-42018,2015-01-14,2015-01-18,Standard Class,PO-18865139,Patrick O'Donnell,Consumer,NaN,Stockton-on-Tees,...,NaN,2616.960,NaN,NaN,NaN,4.0,0.0,1151.400,832.41,Critical
15,4132,IN-2012-DL128657-40918,2012-01-10,2012-01-11,First Class,DL-128657,Dan Lawera,Consumer,NaN,Brisbane,...,NaN,2221.800,NaN,NaN,NaN,7.0,0.0,622.020,810.25,Critical
16,27704,ID-2014-JB1600059-41873,2014-08-22,2014-08-26,Standard Class,JB-1600059,Joy Bell-,Consumer,NaN,Mataram,...,NaN,3701.520,NaN,NaN,NaN,12.0,0.0,1036.080,804.54,Critical
17,13779,IN-2015-BF1100558-42319,2015-11-11,2015-11-15,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,NaN,1869.588,NaN,NaN,NaN,4.0,0.1,186.948,801.66,Critical
19,12069,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,NaN,7958.580,NaN,NaN,NaN,14.0,0.0,3979.080,778.32,Low